# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib {
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/new/OutputFunc.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/new/NextState.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/new/DFlipFlop.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/new/SignZeroExtend.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/new/Select2_MUX.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/new/RegWre_MUX.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/new/RegFile.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/new/PCAddress_MUX.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/new/PC.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/new/IR.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/new/InstructionMemory.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/new/DR.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/new/DBDR.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/new/DataMemory.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/new/ControlUnit.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/new/ALU_A_MUX.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/new/ALU.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/new/CPU.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/imports/new/Display_seg.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/imports/new/debkey.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/imports/new/Counter4.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/imports/new/CLOCK_DIV.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/imports/new/7_SegLED.v
  D:/Vivado_Data/CPU_multi/CPU_multi.srcs/sources_1/imports/new/Show.v
}
read_xdc D:/Vivado_Data/CPU_multi/CPU_multi.srcs/constrs_1/imports/new/Show_CPU.xdc
set_property used_in_implementation false [get_files D:/Vivado_Data/CPU_multi/CPU_multi.srcs/constrs_1/imports/new/Show_CPU.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Vivado_Data/CPU_multi/CPU_multi.cache/wt [current_project]
set_property parent.project_dir D:/Vivado_Data/CPU_multi [current_project]
catch { write_hwdef -file Show.hwdef }
synth_design -top Show -part xc7a35tcpg236-1
write_checkpoint Show.dcp
report_utilization -file Show_utilization_synth.rpt -pb Show_utilization_synth.pb
